package form;


import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author Wiwit Agus Triyanto
 */
public class FormMenu_NIM extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuMDI
     */
    void aktifMenu(Boolean status){ //method aktifMenu untuk mengatur enable true/false sesuai status yang diberikan ketika memanggil method ini
        mnuData.setEnabled(status);
        jtbAnggota.setEnabled(status);
        jtbBuku.setEnabled(status);
    }
    
    public FormMenu_NIM() {
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);  //menampilkan form ini fullscreen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jtbBuku = new javax.swing.JLabel();
        jtbAnggota = new javax.swing.JLabel();
        jtbPeminjaman = new javax.swing.JLabel();
        jtbPengembalian = new javax.swing.JLabel();
        jtbLaporanBuku = new javax.swing.JLabel();
        jtbLaporanAnggota = new javax.swing.JLabel();
        jtbLaporanPeminjaman = new javax.swing.JLabel();
        jtbLaporanPengembalian = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuExit = new javax.swing.JMenuItem();
        mnuData = new javax.swing.JMenu();
        mnuDataBuku = new javax.swing.JMenuItem();
        mnuDataAnggota = new javax.swing.JMenuItem();
        mnuTransaksi = new javax.swing.JMenu();
        mnuPeminjaman = new javax.swing.JMenuItem();
        mnuPengembalian = new javax.swing.JMenuItem();
        mnuLaporan = new javax.swing.JMenu();
        mnuLaporanBuku = new javax.swing.JMenuItem();
        mnuLaporanAnggota = new javax.swing.JMenuItem();
        mnuLaporanPeminjaman = new javax.swing.JMenuItem();
        mnuLaporanPengembalian = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistem Informasi Perpustakaan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jtbBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/100201001.png"))); // NOI18N
        jtbBuku.setText("Data Buku");
        jtbBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbBukuMouseClicked(evt);
            }
        });
        jToolBar1.add(jtbBuku);

        jtbAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/100101001.png"))); // NOI18N
        jtbAnggota.setText("Data Anggota");
        jToolBar1.add(jtbAnggota);

        jtbPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/100301001.png"))); // NOI18N
        jtbPeminjaman.setText("Peminjaman");
        jtbPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbPeminjamanMouseClicked(evt);
            }
        });
        jToolBar1.add(jtbPeminjaman);

        jtbPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/100301002.png"))); // NOI18N
        jtbPengembalian.setText("Pengembalian");
        jToolBar1.add(jtbPengembalian);

        jtbLaporanBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/100402001.png"))); // NOI18N
        jtbLaporanBuku.setText("Laporan Buku");
        jtbLaporanBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbLaporanBukuMouseClicked(evt);
            }
        });
        jToolBar1.add(jtbLaporanBuku);

        jtbLaporanAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/100401001.png"))); // NOI18N
        jtbLaporanAnggota.setText("Laporan Anggota");
        jToolBar1.add(jtbLaporanAnggota);

        jtbLaporanPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/100403002.png"))); // NOI18N
        jtbLaporanPeminjaman.setText("Laporan Peminjaman");
        jtbLaporanPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbLaporanPeminjamanMouseClicked(evt);
            }
        });
        jToolBar1.add(jtbLaporanPeminjaman);

        jtbLaporanPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/100403001.png"))); // NOI18N
        jtbLaporanPengembalian.setText("Laporan Pengembalian");
        jToolBar1.add(jtbLaporanPengembalian);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 884, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        mnuFile.setText("File");

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuExit);

        jMenuBar1.add(mnuFile);

        mnuData.setText("Data");

        mnuDataBuku.setText("Data Buku");
        mnuDataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDataBukuActionPerformed(evt);
            }
        });
        mnuData.add(mnuDataBuku);

        mnuDataAnggota.setText("Data Anggota");
        mnuData.add(mnuDataAnggota);

        jMenuBar1.add(mnuData);

        mnuTransaksi.setText("Transaksi");

        mnuPeminjaman.setText("Peminjaman");
        mnuPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPeminjamanActionPerformed(evt);
            }
        });
        mnuTransaksi.add(mnuPeminjaman);

        mnuPengembalian.setText("Pengembalian");
        mnuTransaksi.add(mnuPengembalian);

        jMenuBar1.add(mnuTransaksi);

        mnuLaporan.setText("Laporan");

        mnuLaporanBuku.setText("Laporan Buku");
        mnuLaporanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLaporanBukuActionPerformed(evt);
            }
        });
        mnuLaporan.add(mnuLaporanBuku);

        mnuLaporanAnggota.setText("Laporan Anggota");
        mnuLaporan.add(mnuLaporanAnggota);

        mnuLaporanPeminjaman.setText("Laporan Peminjaman");
        mnuLaporanPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLaporanPeminjamanActionPerformed(evt);
            }
        });
        mnuLaporan.add(mnuLaporanPeminjaman);

        mnuLaporanPengembalian.setText("Laporan Pengembalian");
        mnuLaporan.add(mnuLaporanPengembalian);

        jMenuBar1.add(mnuLaporan);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuDataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDataBukuActionPerformed
        // TODO add your handling code here:
        IfrmBuku_NIM IfBu = IfrmBuku_NIM.cekForm(); //membuat objek IfBu dari IfrmBuku_NIM dengan tambahan method cekForm
        IfBu.pack();

        if (IfBu.isVisible()){  //jika IfrmBuku_NIM sudah ada maka...
        } else {    //jika IfrmBuku_NIM belum ada maka...
                jDesktopPane1.add(IfBu);    //tambahkan form ke jDesktopPane1
                IfBu.setVisible(true);  //tampilkan form IfrmBuku_NIM
        }
    }//GEN-LAST:event_mnuDataBukuActionPerformed

    private void mnuLaporanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLaporanBukuActionPerformed
        // TODO add your handling code here:
        IlapBuku_NIM IlBu = IlapBuku_NIM.cekForm(); //membuat objek IlBu dari IlapBuku_NIM dengan tambahan method cekForm
        IlBu.pack();

        if (IlBu.isVisible()){  //jika IlapBuku_NIM sudah ada maka...
        } else {    //jika IlapBuku_NIM belum ada maka...
                jDesktopPane1.add(IlBu);    //tambahkan form ke jDesktopPane1
                IlBu.setVisible(true);  //tampilkan form IlapBuku_NIM
        }

        try {
                IlBu.setMaximum(true);  //tampilkan form IlapBuku_NIM secara full screen
        } catch (PropertyVetoException ex){
                Logger.getLogger(FormMenu_NIM.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_mnuLaporanBukuActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        // TODO add your handling code here:
        int tutup = JOptionPane.showConfirmDialog(this, "Anda yakin mau menutup aplikasi ?", 
                "Close", JOptionPane.YES_NO_OPTION);
        if (tutup==0){  //jika pilih yes
            System.exit(0); //menutup aplikasi
        }
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPeminjamanActionPerformed
        // TODO add your handling code here:
        IfrmPeminjaman_NIM IfPem = IfrmPeminjaman_NIM.cekForm();    //membuat objek IfPem dari IfrmPeminjaman_NIM dengan tambahan method cekForm
        IfPem.pack();

        if (IfPem.isVisible()){ //jika IfrmPeminjaman_NIM sudah ada maka...
        } else {    //jika IfrmPeminjaman_NIM belum ada maka...
                jDesktopPane1.add(IfPem);   //tambahkan form ke jDesktopPane1
                IfPem.setVisible(true); //tampilkan form IfrmPeminjaman_NIM
        }
    }//GEN-LAST:event_mnuPeminjamanActionPerformed

    private void jtbLaporanPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbLaporanPeminjamanMouseClicked
        // TODO add your handling code here:
        IlapPeminjaman_NIM IlPe = IlapPeminjaman_NIM.cekForm(); //membuat objek IlPe dari IlapPeminjaman_NIM dengan tambahan method cekForm
        IlPe.pack();

        if (IlPe.isVisible()){  //jika IlapPeminjaman_NIM sudah ada maka...
        } else {    //jika IlapPeminjaman_NIM belum ada maka...
                jDesktopPane1.add(IlPe);    //tambahkan form ke jDesktopPane1
                IlPe.setVisible(true);  //tampilkan form IlapPeminjaman_NIM
        }

        try {
                IlPe.setMaximum(true);  //tampilkan form IlapPeminjaman_NIM secara full screen
        } catch (PropertyVetoException ex){
                Logger.getLogger(FormMenu_NIM.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jtbLaporanPeminjamanMouseClicked

    private void jtbBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbBukuMouseClicked
        // TODO add your handling code here:
        IfrmBuku_NIM IfBu = IfrmBuku_NIM.cekForm(); //membuat objek IfBu dari IfrmBuku_NIM dengan tambahan method cekForm
        IfBu.pack();

        if (IfBu.isVisible()){  //jika IfrmBuku_NIM sudah ada maka...
        } else {    //jika IfrmBuku_NIM belum ada maka...
                jDesktopPane1.add(IfBu);    //tambahkan form ke jDesktopPane1
                IfBu.setVisible(true);  //tampilkan form IfrmBuku_NIM
        }      
    }//GEN-LAST:event_jtbBukuMouseClicked

    private void jtbPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbPeminjamanMouseClicked
        // TODO add your handling code here:
        IfrmPeminjaman_NIM IfPem = IfrmPeminjaman_NIM.cekForm();    //membuat objek IfPem dari IfrmPeminjaman_NIM dengan tambahan method cekForm
        IfPem.pack();

        if (IfPem.isVisible()){ //jika IfrmPeminjaman_NIM sudah ada maka...
        } else {    //jika IfrmPeminjaman_NIM belum ada maka...
                jDesktopPane1.add(IfPem);   //tambahkan form ke jDesktopPane1
                IfPem.setVisible(true); //tampilkan form IfrmPeminjaman_NIM
        }       
    }//GEN-LAST:event_jtbPeminjamanMouseClicked

    private void jtbLaporanBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbLaporanBukuMouseClicked
        // TODO add your handling code here:
        IlapBuku_NIM IlBu = IlapBuku_NIM.cekForm(); //membuat objek IlBu dari IlapBuku_NIM dengan tambahan method cekForm
        IlBu.pack();

        if (IlBu.isVisible()){  //jika IlapBuku_NIM sudah ada maka...
        } else {    //jika IlapBuku_NIM belum ada maka...
                jDesktopPane1.add(IlBu);    //tambahkan form ke jDesktopPane1
                IlBu.setVisible(true);  //tampilkan form IlapBuku_NIM
        }

        try {
                IlBu.setMaximum(true);  //tampilkan form IlapBuku_NIM secara full screen
        } catch (PropertyVetoException ex){
                Logger.getLogger(FormMenu_NIM.class.getName()).log(Level.SEVERE, null, ex);
        }          
    }//GEN-LAST:event_jtbLaporanBukuMouseClicked

    private void mnuLaporanPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLaporanPeminjamanActionPerformed
        // TODO add your handling code here:
        IlapPeminjaman_NIM IlPe = IlapPeminjaman_NIM.cekForm(); //membuat objek IlPe dari IlapPeminjaman_NIM dengan tambahan method cekForm
        IlPe.pack();

        if (IlPe.isVisible()){  //jika IlapPeminjaman_NIM sudah ada maka...
        } else {    //jika IlapPeminjaman_NIM belum ada maka...
                jDesktopPane1.add(IlPe);    //tambahkan form ke jDesktopPane1
                IlPe.setVisible(true);  //tampilkan form IlapPeminjaman_NIM
        }

        try {
                IlPe.setMaximum(true);  //tampilkan form IlapPeminjaman_NIM secara full screen
        } catch (PropertyVetoException ex){
                Logger.getLogger(FormMenu_NIM.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_mnuLaporanPeminjamanActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int tutup = JOptionPane.showConfirmDialog(this, "Anda yakin mau menutup aplikasi ?", 
                "Close", JOptionPane.YES_NO_OPTION);
        if (tutup==0){  //jika pilih yes
            System.exit(0); //menutup aplikasi
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu_NIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu_NIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu_NIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu_NIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu_NIM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jtbAnggota;
    private javax.swing.JLabel jtbBuku;
    private javax.swing.JLabel jtbLaporanAnggota;
    private javax.swing.JLabel jtbLaporanBuku;
    private javax.swing.JLabel jtbLaporanPeminjaman;
    private javax.swing.JLabel jtbLaporanPengembalian;
    private javax.swing.JLabel jtbPeminjaman;
    private javax.swing.JLabel jtbPengembalian;
    private javax.swing.JMenu mnuData;
    private javax.swing.JMenuItem mnuDataAnggota;
    private javax.swing.JMenuItem mnuDataBuku;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuLaporan;
    private javax.swing.JMenuItem mnuLaporanAnggota;
    private javax.swing.JMenuItem mnuLaporanBuku;
    private javax.swing.JMenuItem mnuLaporanPeminjaman;
    private javax.swing.JMenuItem mnuLaporanPengembalian;
    private javax.swing.JMenuItem mnuPeminjaman;
    private javax.swing.JMenuItem mnuPengembalian;
    private javax.swing.JMenu mnuTransaksi;
    // End of variables declaration//GEN-END:variables
}
