package form;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.File;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Wiwit Agus Triyanto
 */
public class IlapBuku_NIM extends javax.swing.JInternalFrame {
    koneksiDB konek = new koneksiDB();
    
    private static IlapBuku_NIM wujudForm;
    
    public static IlapBuku_NIM cekForm() {
	if (wujudForm == null){
            wujudForm = new IlapBuku_NIM();
	}
	return wujudForm;
    }
    /**
     * Creates new form IlapBuku
     */
    public IlapBuku_NIM() {
        initComponents();
        
        cboKategori.removeAllItems();
        cboKategori.addItem("Kode Buku");
        cboKategori.addItem("Judul Buku");
        cboKategori.addItem("Penulis Buku");
        cboKategori.addItem("Penerbit Buku");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboKategori = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtKataKunci = new javax.swing.JTextField();
        btnPreview = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setClosable(true);
        setTitle("Laporan Buku _ NIM");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setDoubleBuffered(false);
        jPanel2.setMaximumSize(new java.awt.Dimension(100, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(392, 45));

        jLabel1.setText("Kategori :");

        cboKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Kata Kunci :");

        btnPreview.setText("PREVIEW");
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKataKunci, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPreview)
                .addGap(182, 182, 182))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtKataKunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPreview))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(300, 300));
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        // TODO add your handling code here:
        String kategoriCetak = "";

        if (cboKategori.getSelectedItem()=="Kode Buku"){
                kategoriCetak = "kode_buku";
        }else if (cboKategori.getSelectedItem()=="Judul Buku"){
                kategoriCetak = "judul_buku";
        }else if (cboKategori.getSelectedItem()=="Penulis Buku"){
                kategoriCetak = "penulis_buku";
        }else if (cboKategori.getSelectedItem()=="Penrbit Buku"){
                kategoriCetak = "penerbit_buku";
        }

        try {
                konek.setKoneksi();
                String filename = System.getProperty("user.dir")+"/src/report/rptBuku_NIM.jasper"; //direktori file report
                HashMap param = new HashMap();

                param.put("kategori", kategoriCetak);   //parameter yang dibuat pada report
                param.put("katakunci", txtKataKunci.getText()); //parameter yang dibuat pada report

                JasperPrint JPrint = JasperFillManager.fillReport(filename, param, konek.setKoneksi());
                JRViewer viewer = new JRViewer(JPrint);

                viewer.setOpaque(true);
                viewer.setVisible(true);

                jScrollPane1.add(viewer);
                jScrollPane1.setViewportView(viewer);
        }catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "ERROR: \n" + ex, "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPreviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPreview;
    private javax.swing.JComboBox<String> cboKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtKataKunci;
    // End of variables declaration//GEN-END:variables
}
